adding ci to make latest helm release
kubearmor/sidekick pull request #3
Opened 2023-09-18 18:34 UTC by Shreyas220

2023-09-19 06:05 UTC, daemon1024 commented
Ref https://github.com/kubearmor/kubearmor/issues/1377

2023-09-19 11:57 UTC, DelusionalOptimist requested changes

2023-09-19 11:57 UTC, DelusionalOptimist commented on .github/workflows/helm-release.yml
> +          sed -i -e "s/version:.*/version: $STABLE_VERSION/g" helm/sidekick/Chart.yaml
Will we be releasing a stable version of sidekick? If yes, then let's also add the STABLE_VERSION file.

2023-09-19 11:57 UTC, DelusionalOptimist commented on .github/workflows/helm-release.yml
> +          token: ${{ secrets.GH_ACCESS_TOKEN }}
This secret needs to be created.
cc @daemon1024

2023-09-19 11:57 UTC, DelusionalOptimist commented on .github/workflows/helm-release.yml
> +          charts_url: https://sidekick.github.io/charts
```suggestion
          charts_url: https://kubearmor.github.io/charts
```

2023-09-26 05:48 UTC, DelusionalOptimist approved these changes

2023-09-26 05:48 UTC, merged